version: '3.7'

services:

  sw-portal-backend:
    container_name: sw-portal-backend
    image: sw-portal-backend:build
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - sw-portal-mongodb
    env_file:
      - 'sw-portal.env'

  sw-portal-mongodb:
    image: sw-portal-mongodb
    container_name: "sw-portal-mongodb"
    build: docker-sw-portal-mongo-db/
    volumes:
      - swapi-mongo-db:/data/db
      - swapi-mongo-config:/data/configdb
    ports:
      - 27017:27017
    env_file:
      - 'sw-portal.env'

volumes:
  swapi-mongo-db:
  swapi-mongo-config:
