server.servlet.context-path: /api

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
    mongodb:
      uri: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${DATABASE_SERVICE_NAME}/${MONGO_INITDB_DATABASE}?authSource=admin"

app-config:
  token:
    secret: "secret"
    expirationTimeMs: 3600000
  frontend:
    url: "http://localhost:4200"
