apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: swapi-mongo-db
  name: swapi-mongo-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sw-portal-mongodb
  name: sw-portal-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sw-portal-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: sw-portal-mongodb
    spec:
      containers:
        - name: sw-portal-mongodb
          image: gcr.io/auspicious-lead-272321/sw-portal-mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: swapi-mongo-db
            - mountPath: /data/configdb
              name: swapi-mongo-db
          envFrom:
            - configMapRef:
                name: sw-portal-backend-config
      restartPolicy: Always
      volumes:
        - name: swapi-mongo-db
          persistentVolumeClaim:
            claimName: swapi-mongo-db-pvc
---

apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sw-portal-mongodb
  name: sw-portal-mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: sw-portal-mongodb
